trigger:
  branches:
    include:
    - main
  paths:
    include:
      - environments/prod
variables:
  - group: remote_state

pool:
  name: maagents
stages:
- stage: BuildStage
  jobs:
  - job: TerraformInitialization
    displayName: Terraform Initialization
    steps:
    - task: TerraformInstaller@1
      displayName: Terraform Install
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/prod'
        backendServiceArm: 'Appserviceconn'
        backendAzureRmResourceGroupName: $(rg_name)
        backendAzureRmStorageAccountName: $(stg_name)
        backendAzureRmContainerName: $(container_name)
        backendAzureRmKey: 'prodapstate.tf'
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/prod'
        environmentServiceNameAzureRM: 'Appserviceconn'
- stage: DeployStage
  dependsOn:
  - BuildStage
  jobs:
  - job: ManualValidation
    displayName: Manual Validation
    pool:
      name: server
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'mayank17717@gmail.com'
        onTimeout: 'resume'
  - job: TerraformApply
    dependsOn:
    - ManualValidation
    pool:
      name: Apagents
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/prod'
        backendServiceArm: 'Appserviceconn'
        backendAzureRmResourceGroupName: 'ggbackend'
        backendAzureRmStorageAccountName: 'ggstginfra'
        backendAzureRmContainerName: 'backend'
        backendAzureRmKey: 'prodapstate.tf'
    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/environments/prod'
        environmentServiceNameAzureRM: 'Appserviceconn'
